### PR TITLE
Update ds3_java_sdk dep

### PR DESCRIPTION
**Pull request by shabtaisharon**

### CODE REVIEW

**Comment by scribe** [comment]
For a project with no subprojects you don't need an all projects block, you can just add to the repositories list.

**Comment by shabtaisharon** [comment]
> For a project with no subprojects you don't need an all projects block, you can just add to the repositories list.

tried that, and it didn't work 🤷🏽‍♂️

**Comment by scribe** [comment]
If you don't mind I'll give this a try first thing tomorrow morning? I'm new to the kts syntax but I'd like to play with it a little?

**Comment by shabtaisharon** [comment]
> If you don't mind I'll give this a try first thing tomorrow morning? I'm new to the kts syntax but I'd like to play with it a little?

sure thing, let me know what you find

**Comment by scribe** [comment]
This is what compiled and built for me

```Kotlin
repositories {
    jcenter()
    maven("https://jitpack.io")
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

val test by tasks.getting(Test::class) {
    useJUnitPlatform { }
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:${project.property("kotlinxCoroutines")}")
    implementation("com.github.ajalt:clikt:${project.property("clikt")}")
    implementation("com.github.spectralogic.ds3_java_sdk:ds3-sdk:${project.property("ds3")}")

    testImplementation("io.kotlintest:kotlintest-runner-junit5:${project.property("kotlintest")}")
    testImplementation("io.mockk:mockk:${project.property("mockk")}")
}

application {
    mainClassName = "com.spectralogic.bp.bench.AppKt"
}
```

**Review by david-limbach — APPROVED** [review]

**Review by scribe — APPROVED** [review]

**Pull request merged**
